<a href="https://colab.research.google.com/github/YonghwanYim/DPRL/blob/main/MDP%2CDP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

P = np.array([[0,1,0,0,0,0],
              [0,0.5,0.3,0.2,0,0],
              [0.5,0.5,0,0,0,0],
              [0,0,0,0.5,0.5,0],
              [0.2,0,0,0,0.7,0.1],
              [0,0,0,0,0,1]])
print(P.sum(axis=1))

[1. 1. 1. 1. 1. 1.]


In [ ]:
v0 = np.array([1,0,0,0,0,0]) # Initial state (rest)
v1 = np.matmul(v0,P) # np.matmul : matrix multiplication. 
print('v1=', v1)
v2 = np.matmul(v1,P)
print('v2=', v2)
v3 = np.matmul(v2,P)
print('v3=', v3)

v1= [0. 1. 0. 0. 0. 0.]
v2= [0.  0.5 0.3 0.2 0.  0. ]
v3= [0.15 0.4  0.15 0.2  0.1  0.  ]


In [ ]:
v = np.array([1,0,0,0,0,0])
for i in range(5000):
    v = np.matmul(v,P)  # V is d (d = dp)
print ('v=', v)

v= [4.10133014e-62 1.28855265e-61 3.97485910e-62 5.45387901e-62
 1.00061246e-61 1.00000000e+00]


In [ ]:
w,v = np.linalg.eig(P.T)  # np.linalg.eig() : return eigenvalue w, eigenvector v   
                          # P.T : matrix 뒤에 .T를 붙이면 transpose matrix. (attribute) 
print(w)
d = np.real_if_close(v[:,0])  # real_if_close() function in Numpy is used to return real parts of an input array
                              # of complex values with all imaginary parts close to zero.
print("d = ", d/d.sum())  # sum to 1

[ 1.        +0.j         -0.18383129+0.35815871j -0.18383129-0.35815871j
  0.97252704+0.j          0.54756777+0.18234902j  0.54756777-0.18234902j]
d =  [0. 0. 0. 0. 0. 1.]


In [ ]:
P = np.array([[0,1,0,0,0,0],
              [0,0.5,0.3,0.2,0,0],
              [0.5,0.5,0,0,0,0],
              [0,0,0,0.5,0.5,0],
              [0.2,0,0,0,0.7,0.1],
              [0.5,0,0,0,0,0.5]])

w,v = np.linalg.eig(P.T)
print(w)
d = np.real_if_close(v[:,2]) 
print("d=", d/d.sum())  # sum to 1

[-0.18616765+0.36182691j -0.18616765-0.36182691j  1.        +0.j
  0.5954077 +0.24703993j  0.5954077 -0.24703993j  0.38151989+0.j        ]
d= [0.12280702 0.35087719 0.10526316 0.14035088 0.23391813 0.04678363]


In [ ]:
R = np.array([1,-2,1.5,0,1.1,0]).T
gamma = 0.99                          # gamma is close to 1 (far-sighted valuation)

In [ ]:
# fixed point iteration
V = np.zeros(6)  # numpy.zeros(shape, dtype=float, order='C', *, like=None); 
                 # shape : int or tuple of ints
                 # numpy.zeros : Return a new array of given shape and type, filled with zeros.
                 # V = [0. 0. 0. 0. 0. 0.]
for i in range(1000):
    V = R + gamma*np.matmul(P,V)  # V = R + gamma*PV (Bellman Equation)
print("V=", V)    

V= [-17.72419461 -18.91333503 -16.63557011 -13.18422697 -13.45058927
 -17.37320647]


In [ ]:
# direct method using inverse
# If there are n states, then the time complexity of this direct method is O(n^3) 
MI = np.linalg.inv(np.eye(6)-gamma*P) # np.eye(n, k=m, dtype=int)
                                      # n : number of rows in the output
                                      # k : index of the diagonal (default : 0) refers to the main diagonal, 
                                      #     a positive value refers to an upper diangonal, and a negative value to a lower diagonal.
V = np.matmul(MI,R)
print("V=", V)

V= [-17.72490151 -18.91404193 -16.63627701 -13.18493386 -13.45129616
 -17.37391336]


In [ ]:
P_easy = np.array([[0.7,0.3,0,0,0,0],
                   [0,0,0.5,0.5,0,0],
                   [0.5,0.5,0,0,0,0],
                   [0,0,0.5,0.5,0,0],
                   [0,0,0,0,0.9,0.1],
                   [0,0,0,0,0,1]])
print(P_easy.sum(axis=1))
R_easy = np.array([1,2,1.5,0,0,0]).T

P_hard = np.array([[0.3,0.7,0,0,0,0],
                   [0,0.7,0,0.3,0,0],
                   [0.5,0.5,0,0,0,0],
                   [0,0.7,0,0.3,0,0],
                   [0.6,0,0,0,0.3,0.1],
                   [0,0,0,0,0,1]])
print(P_hard.sum(axis=1))
R_hard = np.array([1,1,1.5,0,1.7,0]).T

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


### Direct method using matrix inversion
![image.png](attachment:b895a3dc-925d-43b7-94b6-995cf611e794.png)

In [ ]:
V_easy = np.matmul(np.linalg.inv(np.eye(6)-gamma*P_easy),R_easy)
print (V_easy)

[110.86343556 111.2292078  111.43585846 109.2292078    0.
   0.        ]


In [ ]:
V_hard = np.matmul(np.linalg.inv(np.eye(6)-gamma*P_hard),R_hard)
print (V_hard)

[70.72247511 70.3        71.30612518 69.3        62.17517811  0.        ]


### Fibonacci seq.
F(0) = F(1) = 1
F(n) = F(n-1) + F(n-1)

In [ ]:
def fiboRec(n):
    if n <= 1: return n
    return fiboRec(n-1) + fiboRec(n-2)

print (fiboRec(20))

6765


In [ ]:
def fiboForward (N):
    F = [0] * (N+1)
    F[0] = 0
    F[1] = 1
    for n in range(2,N+1):
        F[n] = F[n-1] + F[n-2]
    return F[N]

print (fiboForward(40))

102334155


### Iterative method
![image.png](attachment:c32884eb-e43f-471a-a0d7-aace89f3a921.png)

In [ ]:
V_easy = np.zeros(6)
V_hard = np.zeros(6)
for i in range(1000):
    V_easy = R_easy + gamma*np.matmul(P_easy, V_easy)
    V_hard = R_hard + gamma*np.matmul(P_hard, V_hard)
print (V_easy)
print (V_hard)

[110.85865589 111.22442813 111.43107879 109.22442813   0.
   0.        ]
[70.71945312 70.29697801 71.30310319 69.29697801 62.17258784  0.        ]


## Optimal value function
![image.png](attachment:939abbd2-ea46-476c-be4b-4f4e028cbe18.png)

In [ ]:
V_opt = np.zeros(6)
V = np.zeros((6,2))
for i in range(1000):
    V[:,0] = R_easy + gamma*np.matmul(P_easy, V_opt)
    V[:,1] = R_hard + gamma*np.matmul(P_hard, V_opt)
    V_opt = V.max(axis=1)
print (V_opt)

[121.01972202 121.32311218 121.45965076 119.59724691 104.67378402
   0.        ]


![image.png](attachment:8d5dd8f2-fb62-441a-b437-abd005718317.png)

In [ ]:
Q_opt = np.zeros((6,2))
V_opt = np.zeros(6)
for i in range(1000):
    Q_opt[:,0] = R_easy + gamma*np.matmul(P_easy, V_opt)
    Q_opt[:,1] = R_hard + gamma*np.matmul(P_hard, V_opt)
    V_opt = Q_opt.max(axis=1)
print (Q_opt)
print (V_opt)

[[120.89957951 121.01972202]
 [121.32311218 120.59724691]
 [121.45965076 121.45965076]
 [119.32311218 119.59724691]
 [ 93.26430132 104.67378402]
 [  0.           0.        ]]
[121.01972202 121.32311218 121.45965076 119.59724691 104.67378402
   0.        ]


![image.png](attachment:929773b3-689e-4c52-8ca3-e996c1611ffa.png)

In [ ]:
def move(i,j,h,w,a):
    ip, jp = i, j
    if a == 0 :  # left
        if j > 0: jp = j-1
    elif a == 1: # right
        if j < w-1: jp = j+1
    elif a == 2: # up
        if i > 0: ip = i-1
    elif a == 3: # down
        if i < h-1: ip = i+1
    return ip, jp
    
def gridworldGetP(w,h,a,terminal=[]):
    n = w*h
    P = np.zeros((n,n))
    for i in range(h):
        for j in range(w):
            k = i*w + j
            if k in terminal: continue
            ip,jp = move(i,j,h,w,a)
            kp = ip*w + jp
            P[k,kp] = 1
    for k in terminal:
        P[k,k] = 1
    return P

# P = gridworldGetP(4,4,0,[0,15])
# print (P)
# print (P.sum(axis=1))

In [ ]:
# make model for shortest path
terminal = [0,15]
P = []
for a in range(4):
    Pa = gridworldGetP(4,4,a,terminal)
    P.append(Pa)
    
R = np.full((16,4),-1)
for s in terminal: 
    R[s,:] = 0
    
gamma = 1

# random policy
pi = np.full((16,4),0.25)

In [ ]:
R_rand = (pi * R).sum(axis=1)
print (R_rand)

P_rand = np.zeros((16,16))
for s in range(16):
    for a in range(4):
        P_rand[s,:] += pi[s,a] * P[a][s,:]
print (P_rand)
print (P_rand.sum(axis=1))

# iterative evaluation of random policy (synch. backup, matrix version)
V_rand = np.zeros(16)
for i in range(20):
    V_rand = R_rand + gamma*np.matmul(P_rand, V_rand)
    print (V_rand.reshape(4,4))

[ 0. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  0.]
[[1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.25 0.25 0.25 0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.   0.25 0.25 0.25 0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.   0.   0.25 0.5  0.   0.   0.   0.25 0.   0.   0.   0.   0.   0.
  0.   0.  ]
 [0.25 0.   0.   0.   0.25 0.25 0.   0.   0.25 0.   0.   0.   0.   0.
  0.   0.  ]
 [0.   0.25 0.   0.   0.25 0.   0.25 0.   0.   0.25 0.   0.   0.   0.
  0.   0.  ]
 [0.   0.   0.25 0.   0.   0.25 0.   0.25 0.   0.   0.25 0.   0.   0.
  0.   0.  ]
 [0.   0.   0.   0.25 0.   0.   0.25 0.25 0.   0.   0.   0.25 0.   0.
  0.   0.  ]
 [0.   0.   0.   0.   0.25 0.   0.   0.   0.25 0.25 0.   0.   0.25 0.
  0.   0.  ]
 [0.   0.   0.   0.   0.   0.25 0.   0.   0.25 0.   0.25 0.   0.   0.25
  0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.25 0.   0.25 0.   0.
  0.25 0.  ]
 [0.   0.   0.   0.

In [ ]:
# iterative policy evaluation (asynch. backup)
def policyEvaluation(P, R, gamma, pi, V, k):
    for i in range(k):
        for s in range(16):
            sum = 0.0
            for a in range(4):
                sum += pi[s,a]*(R[s,a]+gamma*np.dot(P[a][s,:],V))
            V[s] = sum
    return V

V = policyEvaluation(P, R, gamma, pi, np.zeros(16), 20)
print (V.reshape(4,4))

[[  0.         -11.42591538 -16.29940807 -17.92681232]
 [-11.42591538 -14.84125831 -16.57033147 -16.60954761]
 [-16.29940807 -16.57033147 -15.10598674 -11.83929409]
 [-17.92681232 -16.60954761 -11.83929409   0.        ]]


In [ ]:
# greedy policy improvement
def getQ(V, P, R, gamma):
    Q = np.zeros((16,4))
    for s in range(16):
        for a in range(4):
            Q[s,a] = R[s,a] + gamma*np.dot(P[a][s,:],V)
    return Q

def greedy(Q):
    pi = np.zeros((16,4))
    for s in range(16):
        a = np.argmax(Q[s,:])
        pi[s,a] = 1
    return pi

def greedyPolicy(V, P, R, gamma):
    Q = getQ(V, P, R, gamma)
    # print(Q)
    pi = greedy(Q)
    # print (pi)
    return pi

In [ ]:
# Policy iteration
k = 1
V = np.zeros(16)
for i in range(100):
    V = policyEvaluation(P, R, gamma, pi, V, k)
    print (V.reshape(4,4))
    pi_old = pi
    pi = greedyPolicy(V, P, R, gamma)
    if np.equal(pi, pi_old).all():
        break
dpi = np.argmax(pi,axis=1)
print (dpi.reshape(4,4))


[[ 0.        -1.        -1.25      -1.3125   ]
 [-1.        -1.5       -1.6875    -1.75     ]
 [-1.25      -1.6875    -1.84375   -1.8984375]
 [-1.3125    -1.75      -1.8984375  0.       ]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -1.]
 [-3. -4. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[0 0 0 0]
 [2 0 0 3]
 [2 0 1 3]
 [1 1 1 0]]


In [ ]:
# value iteration (synchronous backup)
V = np.zeros(16)
Va = np.zeros(4)
for k in range(5):
    Vnew = np.zeros(16)
    for s in range(16):
        for a in range(4):
            Va[a] = R[s,a] + gamma*np.dot(P[a][s,:], V)
        Vnew[s] = np.max(Va)
    V = Vnew
    print (V.reshape(4,4))

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


In [ ]:
# Asynchronous VI : In-place VI
V = np.zeros(16)
Va = np.zeros(4)
for k in range(100):
    print (V.reshape(4,4))
    changed = False
    for s in range(16):
        for a in range(4):
            Va[a] = R[s,a] + gamma*np.dot(P[a][s,:], V)
        old = V[s]
        V[s] = np.max(Va)
        if abs(V[s]-old) > 0.0001:
            changed = True
    if not changed:
        break

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


### Shortest path
![image.png](attachment:fcb79fb5-4deb-4538-99e8-46cd5e97ef6a.png)

In [ ]:
# make model for shortest path
terminal = [0]
P = []
for a in range(4):
    Pa = gridworldGetP(4,4,a,terminal)
    P.append(Pa)
    
R = np.full((16,4),-1)
for s in terminal: 
    R[s,:] = 0
    
gamma = 1

In [ ]:
# Synchronous VI
V = np.zeros(16)
Va = np.zeros(4)
for k in range(6):
    Vnew = np.zeros(16)
    for s in range(16):
        for a in range(4):
            Va[a] = R[s,a] + gamma*np.dot(P[a][s,:], V)
        Vnew[s] = np.max(Va)
    V = Vnew
    print (V.reshape(4,4))

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]
[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -3.]
 [-2. -3. -3. -3.]
 [-3. -3. -3. -3.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -4.]
 [-3. -4. -4. -4.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -5.]]
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]


In [ ]:
# Asynchronous VI : In-place VI
V = np.zeros(16)
for k in range(6):
    for s in range(16):
        for a in range(4):
            Va[a] = R[s] + gamma*np.dot(P[a][s,:], V)
        V[s] = np.max(Va)
    print (V.reshape(4,4))

ValueError: ignored